env = Environment(TARGET_ARCH='amd64', MSVC_VERSION='14.2')

env['CXX'] = '$CC'
env.Append(CCFLAGS=['/MD', '/nologo', '/D_SCL_SECURE_NO_WARNINGS', '/D_CRT_SECURE_NO_WARNINGS', '/Zi', '/Fd${TARGET}.pdb', '/EHsc'],
           CPPPATH=['C:\\Users\\gkoge\\Desktop\\BVP_class\\BVP_code\\ModifiedDampedNewtonsMethod\\toolsFolder\\eigen-3.4.0'],
           INCLUDEPATH=['C:\\Users\\gkoge\\Desktop\\BVP_class\\BVP_code\\ModifiedDampedNewtonsMethod\\toolsFolder\\eigen-3.4.0'],
           LIBS=[],
           LIBPATH=['C:\\Users\\gkoge\\Desktop\\BVP_class\\BVP_code\\ModifiedDampedNewtonsMethod\\toolsFolder\\eigen-3.4.0'],
           LINKFLAGS=['/nologo', '/DEBUG', '/NODEFAULTLIB:MSVCRTD'],
           FRAMEWORKS=[])

program = env.Program('BVP', ['mainBVP.cpp', 'BoundaryValueProblem.cpp', 'Mesh.cpp', 'Residual.cpp', 'Jacobian.cpp'])
Default(program)